var searchData=
[
  ['scatter_5fadd_5flocal_5fcontext_5ft',['scatter_add_local_context_t',['../db/d06/structscatter__add__local__context__t.html',1,'']]],
  ['scatter_5fnd_5flocal_5fcontext_5ft',['scatter_nd_local_context_t',['../d5/d2b/structscatter__nd__local__context__t.html',1,'']]],
  ['selu_5flocal_5fcontext_5ft',['selu_local_context_t',['../df/d95/structselu__local__context__t.html',1,'']]],
  ['shift_5flocal_5fcontext_5ft',['shift_local_context_t',['../dd/dc0/structshift__local__context__t.html',1,'']]],
  ['sign_5flocal_5fcontext_5ft',['sign_local_context_t',['../de/de1/structsign__local__context__t.html',1,'']]],
  ['sink_5flocal_5fcontext_5ft',['sink_local_context_t',['../d8/de8/structsink__local__context__t.html',1,'']]],
  ['slice_5flocal_5fcontext_5ft',['slice_local_context_t',['../df/d15/structslice__local__context__t.html',1,'']]],
  ['softmax_5fcross_5fentropy_5flocal_5fcontext_5ft',['softmax_cross_entropy_local_context_t',['../d9/d84/structsoftmax__cross__entropy__local__context__t.html',1,'']]],
  ['softmax_5flocal_5fcontext_5ft',['softmax_local_context_t',['../d1/d4a/structsoftmax__local__context__t.html',1,'']]],
  ['sort_5flocal_5fcontext_5ft',['sort_local_context_t',['../db/de5/structsort__local__context__t.html',1,'']]],
  ['split_5flocal_5fcontext_5ft',['split_local_context_t',['../dc/d13/structsplit__local__context__t.html',1,'']]],
  ['st_5frt_5ffunction_5ft',['st_rt_function_t',['../dc/d33/structst__rt__function__t.html',1,'']]],
  ['stack_5flocal_5fcontext_5ft',['stack_local_context_t',['../d2/da5/structstack__local__context__t.html',1,'']]],
  ['stft_5flocal_5fcontext_5ft',['stft_local_context_t',['../d9/da0/structstft__local__context__t.html',1,'']]],
  ['sub2_5flocal_5fcontext_5ft',['sub2_local_context_t',['../da/de3/structsub2__local__context__t.html',1,'']]],
  ['sum_5flocal_5fcontext_5ft',['sum_local_context_t',['../d4/da6/structsum__local__context__t.html',1,'']]],
  ['sum_5fpooling_5flocal_5fcontext_5ft',['sum_pooling_local_context_t',['../dd/dd3/structsum__pooling__local__context__t.html',1,'']]],
  ['sync_5fbatch_5fnormalization_5flocal_5fcontext_5ft',['sync_batch_normalization_local_context_t',['../df/d71/structsync__batch__normalization__local__context__t.html',1,'']]]
];
