var searchData=
[
  ['r_5fdiv_5fscalar_5flocal_5fcontext_5ft',['r_div_scalar_local_context_t',['../dc/db6/structr__div__scalar__local__context__t.html',1,'']]],
  ['r_5fpow_5fscalar_5flocal_5fcontext_5ft',['r_pow_scalar_local_context_t',['../d1/d85/structr__pow__scalar__local__context__t.html',1,'']]],
  ['r_5fsub_5fscalar_5flocal_5fcontext_5ft',['r_sub_scalar_local_context_t',['../df/dae/structr__sub__scalar__local__context__t.html',1,'']]],
  ['rand_5flocal_5fcontext_5ft',['rand_local_context_t',['../d9/df6/structrand__local__context__t.html',1,'']]],
  ['randint_5flocal_5fcontext_5ft',['randint_local_context_t',['../d3/d29/structrandint__local__context__t.html',1,'']]],
  ['randn_5flocal_5fcontext_5ft',['randn_local_context_t',['../d4/d04/structrandn__local__context__t.html',1,'']]],
  ['random_5fchoice_5flocal_5fcontext_5ft',['random_choice_local_context_t',['../de/df7/structrandom__choice__local__context__t.html',1,'']]],
  ['random_5fcrop_5flocal_5fcontext_5ft',['random_crop_local_context_t',['../db/d34/structrandom__crop__local__context__t.html',1,'']]],
  ['random_5fflip_5flocal_5fcontext_5ft',['random_flip_local_context_t',['../dc/d13/structrandom__flip__local__context__t.html',1,'']]],
  ['random_5fshift_5flocal_5fcontext_5ft',['random_shift_local_context_t',['../d0/d89/structrandom__shift__local__context__t.html',1,'']]],
  ['relu_5flocal_5fcontext_5ft',['relu_local_context_t',['../d8/df3/structrelu__local__context__t.html',1,'']]],
  ['reset_5finf_5flocal_5fcontext_5ft',['reset_inf_local_context_t',['../d6/dca/structreset__inf__local__context__t.html',1,'']]],
  ['reset_5fnan_5flocal_5fcontext_5ft',['reset_nan_local_context_t',['../d4/dc6/structreset__nan__local__context__t.html',1,'']]],
  ['reshape_5flocal_5fcontext_5ft',['reshape_local_context_t',['../d4/dda/structreshape__local__context__t.html',1,'']]],
  ['rnn_5flocal_5fcontext_5ft',['rnn_local_context_t',['../dd/df0/structrnn__local__context__t.html',1,'']]],
  ['rt_5fcontext_5ft',['rt_context_t',['../db/ded/structrt__context__t.html',1,'']]],
  ['rt_5ffunction_5fcallback_5ft',['rt_function_callback_t',['../d2/d4b/structrt__function__callback__t.html',1,'']]],
  ['rt_5ffunction_5fcontext_5ft',['rt_function_context_t',['../d6/df3/structrt__function__context__t.html',1,'']]],
  ['rt_5flist_5ft',['rt_list_t',['../d6/d3a/structrt__list__t.html',1,'']]],
  ['rt_5fvariable_5fbuffer_5fcontext_5ft',['rt_variable_buffer_context_t',['../de/dca/structrt__variable__buffer__context__t.html',1,'']]],
  ['rt_5fvariable_5ft',['rt_variable_t',['../da/d92/structrt__variable__t.html',1,'']]]
];
