var searchData=
[
  ['rand',['Rand',['../classnbla_1_1Rand.html',1,'nbla']]],
  ['randbeta',['RandBeta',['../classnbla_1_1RandBeta.html',1,'nbla']]],
  ['randbinomial',['RandBinomial',['../classnbla_1_1RandBinomial.html',1,'nbla']]],
  ['randgamma',['RandGamma',['../classnbla_1_1RandGamma.html',1,'nbla']]],
  ['randint',['Randint',['../classnbla_1_1Randint.html',1,'nbla']]],
  ['randn',['Randn',['../classnbla_1_1Randn.html',1,'nbla']]],
  ['randomchoice',['RandomChoice',['../classnbla_1_1RandomChoice.html',1,'nbla']]],
  ['randomcrop',['RandomCrop',['../classnbla_1_1RandomCrop.html',1,'nbla']]],
  ['randomerase',['RandomErase',['../classnbla_1_1RandomErase.html',1,'nbla']]],
  ['randomflip',['RandomFlip',['../classnbla_1_1RandomFlip.html',1,'nbla']]],
  ['randomshift',['RandomShift',['../classnbla_1_1RandomShift.html',1,'nbla']]],
  ['rdivscalar',['RDivScalar',['../classRDivScalar.html',1,'']]],
  ['reducemean',['ReduceMean',['../classnbla_1_1ReduceMean.html',1,'nbla']]],
  ['reducesum',['ReduceSum',['../classnbla_1_1ReduceSum.html',1,'nbla']]],
  ['relu',['ReLU',['../classnbla_1_1ReLU.html',1,'nbla']]],
  ['reshape',['Reshape',['../classnbla_1_1Reshape.html',1,'nbla']]],
  ['rmsprop',['RMSprop',['../classnbla_1_1RMSprop.html',1,'nbla']]],
  ['rnn',['RNN',['../classnbla_1_1RNN.html',1,'nbla']]],
  ['round',['Round',['../classRound.html',1,'']]],
  ['rpowscalar',['RPowScalar',['../classRPowScalar.html',1,'']]],
  ['rsubscalar',['RSubScalar',['../classRSubScalar.html',1,'']]]
];
