var searchData=
[
  ['selu',['SELU',['../d8/d7a/group__SELU.html',1,'']]],
  ['shape_20function',['Shape Function',['../d5/dd5/group__ShapeFunction.html',1,'']]],
  ['shift',['Shift',['../d3/d46/group__Shift.html',1,'']]],
  ['sigmoid',['Sigmoid',['../d2/d49/group__Sigmoid.html',1,'']]],
  ['sigmoidcrossentropy',['SigmoidCrossEntropy',['../d1/d39/group__SigmoidCrossEntropy.html',1,'']]],
  ['sign',['Sign',['../dc/d45/group__Sign.html',1,'']]],
  ['sin',['Sin',['../de/da2/group__Sin.html',1,'']]],
  ['sinh',['Sinh',['../da/d2c/group__Sinh.html',1,'']]],
  ['sink',['Sink',['../d1/d4e/group__Sink.html',1,'']]],
  ['slice',['Slice',['../df/d63/group__Slice.html',1,'']]],
  ['softmax',['Softmax',['../d7/d4e/group__Softmax.html',1,'']]],
  ['softmaxcrossentropy',['SoftmaxCrossEntropy',['../d2/db6/group__SoftmaxCrossEntropy.html',1,'']]],
  ['special_20use',['Special Use',['../d3/de6/group__SpecialUse.html',1,'']]],
  ['spectral_20operation',['Spectral Operation',['../d0/d72/group__SpectralOperation.html',1,'']]],
  ['split',['Split',['../d4/ddf/group__Split.html',1,'']]],
  ['squarederror',['SquaredError',['../d7/da7/group__SquaredError.html',1,'']]],
  ['stack',['Stack',['../dd/d32/group__Stack.html',1,'']]],
  ['stochasticity',['Stochasticity',['../d5/d7c/group__Stochasticity.html',1,'']]],
  ['sub2',['Sub2',['../d3/d12/group__Sub2.html',1,'']]],
  ['sum',['Sum',['../de/d3a/group__Sum.html',1,'']]],
  ['sumpooling',['SumPooling',['../d5/d78/group__SumPooling.html',1,'']]],
  ['swish',['Swish',['../d3/d80/group__Swish.html',1,'']]]
];
