var searchData=
[
  ['scatteradd_6670',['ScatterAdd',['../d3/df6/group__ScatterAdd.html',1,'']]],
  ['scatternd_6671',['ScatterNd',['../d4/d81/group__ScatterNd.html',1,'']]],
  ['searchsorted_6672',['SearchSorted',['../d7/d5a/group__SearchSorted.html',1,'']]],
  ['selu_6673',['SELU',['../d8/d7a/group__SELU.html',1,'']]],
  ['shape_6674',['Shape',['../d7/d1d/group__Shape.html',1,'']]],
  ['shape_20function_6675',['Shape Function',['../d5/dd5/group__ShapeFunction.html',1,'']]],
  ['shift_6676',['Shift',['../d3/d46/group__Shift.html',1,'']]],
  ['sigmoid_6677',['Sigmoid',['../d2/d49/group__Sigmoid.html',1,'']]],
  ['sigmoidcrossentropy_6678',['SigmoidCrossEntropy',['../d1/d39/group__SigmoidCrossEntropy.html',1,'']]],
  ['sign_6679',['Sign',['../dc/d45/group__Sign.html',1,'']]],
  ['signal_20processing_6680',['Signal Processing',['../de/d0f/group__SignalProcessing.html',1,'']]],
  ['sin_6681',['Sin',['../de/da2/group__Sin.html',1,'']]],
  ['sinc_6682',['Sinc',['../d3/da4/group__Sinc.html',1,'']]],
  ['sinh_6683',['Sinh',['../da/d2c/group__Sinh.html',1,'']]],
  ['sink_6684',['Sink',['../d1/d4e/group__Sink.html',1,'']]],
  ['slice_6685',['Slice',['../df/d63/group__Slice.html',1,'']]],
  ['softmax_6686',['Softmax',['../d7/d4e/group__Softmax.html',1,'']]],
  ['softmaxcrossentropy_6687',['SoftmaxCrossEntropy',['../d2/db6/group__SoftmaxCrossEntropy.html',1,'']]],
  ['softplus_6688',['SoftPlus',['../d7/dc0/group__SoftPlus.html',1,'']]],
  ['softsign_6689',['SoftSign',['../d6/d6a/group__SoftSign.html',1,'']]],
  ['sort_6690',['Sort',['../da/d2c/group__Sort.html',1,'']]],
  ['special_20use_6691',['Special Use',['../d3/de6/group__SpecialUse.html',1,'']]],
  ['spectralnorm_6692',['SpectralNorm',['../df/d14/group__SpectralNorm.html',1,'']]],
  ['split_6693',['Split',['../d4/ddf/group__Split.html',1,'']]],
  ['squarederror_6694',['SquaredError',['../d7/da7/group__SquaredError.html',1,'']]],
  ['stack_6695',['Stack',['../dd/d32/group__Stack.html',1,'']]],
  ['stft_6696',['STFT',['../d7/d0f/group__STFT.html',1,'']]],
  ['stochasticity_6697',['Stochasticity',['../d5/d7c/group__Stochasticity.html',1,'']]],
  ['sub2_6698',['Sub2',['../d3/d12/group__Sub2.html',1,'']]],
  ['sum_6699',['Sum',['../de/d3a/group__Sum.html',1,'']]],
  ['sumpooling_6700',['SumPooling',['../d5/d78/group__SumPooling.html',1,'']]],
  ['swish_6701',['Swish',['../d3/d80/group__Swish.html',1,'']]],
  ['syncbatchnormalization_6702',['SyncBatchNormalization',['../d9/d02/group__SyncBatchNormalization.html',1,'']]]
];
