var searchData=
[
  ['batchcholesky_6496',['BatchCholesky',['../d2/ddc/group__BatchCholesky.html',1,'']]],
  ['batchdet_6497',['BatchDet',['../dd/d72/group__BatchDet.html',1,'']]],
  ['batchinv_6498',['BatchInv',['../dc/dfd/group__BatchInv.html',1,'']]],
  ['batchlogdet_6499',['BatchLogdet',['../da/d34/group__BatchLogdet.html',1,'']]],
  ['batchmatmul_6500',['BatchMatmul',['../d7/ded/group__BatchMatmul.html',1,'']]],
  ['batchnormalization_6501',['BatchNormalization',['../d1/df1/group__BatchNormalization.html',1,'']]],
  ['bcadd2_6502',['BcAdd2',['../db/d73/group__BcAdd2.html',1,'']]],
  ['binaryconnectaffine_6503',['BinaryConnectAffine',['../d3/dd6/group__BinaryConnectAffine.html',1,'']]],
  ['binaryconnectconvolution_6504',['BinaryConnectConvolution',['../d1/d9d/group__BinaryConnectConvolution.html',1,'']]],
  ['binarycrossentropy_6505',['BinaryCrossEntropy',['../db/d70/group__BinaryCrossEntropy.html',1,'']]],
  ['binaryerror_6506',['BinaryError',['../d4/d46/group__BinaryError.html',1,'']]],
  ['binarysigmoid_6507',['BinarySigmoid',['../d6/d09/group__BinarySigmoid.html',1,'']]],
  ['binarytanh_6508',['BinaryTanh',['../d3/d9a/group__BinaryTanh.html',1,'']]],
  ['binaryweightaffine_6509',['BinaryWeightAffine',['../d2/d92/group__BinaryWeightAffine.html',1,'']]],
  ['binaryweightconvolution_6510',['BinaryWeightConvolution',['../db/d0f/group__BinaryWeightConvolution.html',1,'']]],
  ['boolfill_6511',['BoolFill',['../d8/def/group__BoolFill.html',1,'']]],
  ['boolgather_6512',['BoolGather',['../d0/d1f/group__BoolGather.html',1,'']]],
  ['boolscatter_6513',['BoolScatter',['../d7/d23/group__BoolScatter.html',1,'']]],
  ['broadcast_6514',['Broadcast',['../df/dd1/group__Broadcast.html',1,'']]],
  ['broadcastto_6515',['BroadcastTo',['../d3/de4/group__BroadcastTo.html',1,'']]]
];
